### ISSUE TITLE
Add Additional Install Instructions to the README

### ISSUE THREAD

**Issue by wpb1** [dfinity/quill#147]
I recently set up a new computer and came to this repository to get the latest version of `quill`.  I had trouble with the installation that required me to get assistance from @chmllr.  The solution was relatively simple and I thought it might be helpful to document it in the [README.md](https://github.com/dfinity/quill#readme) file.  

I first attempted to [Build](https://github.com/dfinity/quill#build) the quill file using rustup as well as Nix according to the instructions.  In both cases I ran into errors even though I installed the latest version of both rustup and Nix for this purpose.  I didn't troubleshoot further since I assumed I could just copy/paste the binary.  

I am running the Ubuntu distribution of Linux on Windows with WSL2.  Hence, I downloaded the [quill-linux-x86_64](https://github.com/dfinity/quill/releases/download/v0.3.1/quill-linux-x86_64) binary from the [release](https://github.com/dfinity/quill/releases) link in the [Download](https://github.com/dfinity/quill#download) section.  Once on my computer, I changed the filename to simply `quill` and moved it into the `Ubuntu\home\<user>\bin` folder, which is where the `dfx` binary is also installed.  After closing the terminal and opening a new terminal, I tried running the `quill --version` command and received an error (see image below).  This is where I got stuck and needed to reach out to Christian.  He immediately recognized that I needed to run the `chmod +x ./quill` command in order to change the permissions assigned to the file by default.  At my current level of developer experience, I would not have figured this out on my own.  Hence, it would be nice if this instruction could be provided in the [Download](https://github.com/dfinity/quill#download) section of the README file. 

![image](https://user-images.githubusercontent.com/85973797/211201927-ce3ae808-0527-472a-b95a-eed9a60fcb7d.png)

**Comment by adamspofford-dfinity** [comment]
Fixed in #149.
