### ISSUE TITLE
"Months" have weak meaning when it comes to dissolve delays

### ISSUE THREAD

**Issue by jwiegley** [dfinity/quill#24]
In all of our literature we talk about "6 months" being the minimum dissolve delay that can accrue voting rewards, except that we use seconds in the `quill` user interface and don't specify which six months, in which year, are being used to measure those seconds.

We should both document that 15_778_800 seconds is the actual minimum number of seconds required to vote, and also provide a constant string such as SIX_MONTHS that can be passed in the place of a seconds figure, to make it easier for users. Better still would be to add a simple expression parser that handles basic arithmetic, and then make all the same constants we use in Rust available, e.g.:

```
quill neuron-manage --additional-dissolve-delay-seconds '(8 * MONTHS) + 2 YEARS'
```

**Comment by chmllr** [comment]
I agree that having seconds only is not convenient and having a simple and unambiguous relative time notation would be great. Not sure about having arithmetical expressions though as this will require significant testing efforts and even if we get it 100% correct, it's easy to imagine simple user errors like forgetting parenthesis, mixing up the operator precedence, etc, which will lead to locking your neuron for way longer than you wanted to. I personally think we should not to add this complexity to the core tool. But something like `--additional-dissolve-delay '2 YEARS'` seems like a great idea. What do others think? @dfinity/self-custody

**Comment by egeyar** [comment]
I find Christian's argument quite reasonable. It would be quite bad to have a bug in the computation of the delay, so being minimalist seems safer to me as well. Moreover, I believe it would be enough for users if we just defined the units and let them specify one number and one unit.

**Comment by jwiegley** [comment]
I've added some symbolic constants just to help the most common cases, like `SIX_MONTHS` and `EIGHT_YEARS`, but haven't implemented a full calculational interpreter. This also helps security readers to know what is precisely mean by "six months" from the perspective of governance.
