### ISSUE TITLE
neuron-manage should accept neuron id with _ separator

### ISSUE THREAD

**Issue by timohanke** [dfinity/quill#28]
From `dfx` we are used to read and provide nat64s (such as neuron ids) with a bunch of _ separators inside them. It would be great if neuron ids could be copy-pasted from candid output and be accepted as is by `quill neuron-manage`.

**Comment by chmllr** [comment]
Thanks @timohanke, that's a good idea. I added this in https://github.com/dfinity/quill/pull/39. I hope to merge it next week.

**Comment by timohanke** [comment]
Feature got merged in #39.
