### ISSUE TITLE
Make --name accept empty string

### ISSUE THREAD

**Issue by timohanke** [dfinity/quill#29]
The neuron-stake command takes a neuron name and converts it to a nonce. It would be natural if the empty string was converted to the nonce value 0. Currently, clap seems to prevent the empty string from being accepted. It would be good to remove that restriction.

**Comment by chmllr** [comment]
I had some thoughts on this already and suggest instead of `--name ""` being implicitly converted to 0, we just add an alternative way of specifying a numeric nonce. `--name` and `--nonce` should be mutually exclusive parameters. Hence, `--nonce 0` would solve your problem, right @timohanke ?

**Comment by chmllr** [comment]
https://github.com/dfinity/quill/pull/31

**Comment by timohanke** [comment]
Even if `--nonce` exists I would still keep this issue up (maybe lower priority) because it is more consistent with the 0-byte left padding to interpret the empty string as nonce 0.

**Comment by chmllr** [comment]
@timohanke https://github.com/dfinity/quill/pull/31 is merged now and you can use `--nonce`. I'm still not sure about accepting a special case with an empty name: from the user perspective it will be absolutely not clear what memo will be generated from it (the user wouldn't know anything about the left-padding). And if you care to give an explicit name to the neuron, why you let it empty?
