### ISSUE TITLE
Do not output Candid IDL from queries, but JSON

### ISSUE THREAD

**Issue by jwiegley** [dfinity/quill#61]

**Comment by adamspofford-dfinity** [comment]
Is this necessary? Candid can be clearer about enums and principals, and for a user who hasn't encountered its syntax it is not exactly unintuitive.

**Comment by sasa-tomic** [comment]
I would second that request. Candid can be clearer in some cases but is noisier in _all_ cases.
From my point of view, JSON should be the default, Candid should be possible. So one should be able to provide an argument e.g. `--format candid` and pick the output format.

**Comment by adamspofford-dfinity** [comment]
Obsoleted by queries outputting user-friendly data instead of IDL.
