### ISSUE TITLE
quill cannot send on zsh

### ISSUE THREAD

**Issue by timohanke** [dfinity/quill#86]
It might be related to zsh: the observed behavior is that it prompts for [y/N] but doesn't wait for a key press. Instead it terminates and the message does not get sent.

**Comment by chmllr** [comment]
It's impossible to tell if it's a bug or not without seeing which command exactly does not work. E.g. if you pipe something into `quill send` then the user prompt indeed does not appear as it seems to be "fed" from the pipe for some reason. IDK at this point if this can be easily fix and if it is a problem of zsh, Rust stdlib or quill. We can keep the issue though, but please extend it with more info maybe?

**Comment by adamspofford-dfinity** [comment]
Fixed (in a sense) in #165.
