### ISSUE TITLE
list-proposals does not return "deadline_timestamp_seconds"

### ISSUE THREAD

**Issue by jbroudou** [dfinity/quill#98]
When calling the "list_proposals" method of https://bmht6-iiaaa-aaaad-qabeq-cai.raw.ic0.app/principal/rrkah-fqaaa-aaaaa-aaaaq-cai I can see that deadline_timestamp_seconds is returned in the response (see below). This is missing when invoking the same method via quill.

"proposal_info": [
    {
      "id": [
        {
          "id": "43574"
        }
      ],
      "status": 1,
      "topic": 8,
      "failure_reason": [],
      "ballots": [],
      "proposal_timestamp_seconds": "1644281103",
      "reward_event_round": "0",
      "deadline_timestamp_seconds": [
        "1644626703"
      ],

**Comment by adamspofford-dfinity** [comment]
Cannot reproduce on latest version of quill.
